PATCH /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/cancellations/85e3350a80ab47548c6933c01fe8b85e?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/ff97e1247a614c048b4fb5527ea5b9f1?KeyID=172d32c8&Signature=YkZ8ZOqiheBFefmKSj56cJdeq7CD4OaAzCaSiQn13dny%2FeYiS9ls2WqVvIX5qAV4DUgoej8pUUr5oI4L8DD8Cw%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:47.635718+03:00", 
        "dateModified": "2018-07-05T15:44:47.635740+03:00", 
        "id": "c4eb9970b6694811bb16c782ca84b967"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a9c682c7a1247409b01e5df7baa67e6?KeyID=172d32c8&Signature=QMKBUG9URxfQnxjPVz00I7zJwZljZ2HV%2F5hh9uYg4cg7kmVCpvWKIQ%252Bf1bPSuVgzflIci5Z93BnbFGI7jXVhAg%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:47.635718+03:00", 
        "dateModified": "2018-07-05T15:44:47.965256+03:00", 
        "id": "c4eb9970b6694811bb16c782ca84b967"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2018-07-05T15:44:48.136682+03:00", 
    "cancellationOf": "tender", 
    "id": "85e3350a80ab47548c6933c01fe8b85e"
  }
}

