PATCH /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/cancellations/5b7b7e9fbe0340f5ad88eccc7ced1c51?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7fad0841b4c04a34a0781b5d9df39299?KeyID=7149c8cc&Signature=eUJfguREMN77TKqJoyrlz%2FApEeUDvgZU9XhPBnaBegBMH8jSxwBRpzwr87dhEd3bK16kfFwoUn3JVSWqae6OAA%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:07.723456+03:00", 
        "dateModified": "2018-05-28T19:03:07.723479+03:00", 
        "id": "45baf4951469459394de757f4c50b394"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f3b6995285c4491db7d8df528e48aeb4?KeyID=7149c8cc&Signature=V21tF8lhwqSmzPprBLYz8aNyWVvyDYsRc5wzBCakSQ8y6l3iCExbaMwc954xcldHZjLdRT54YkBNR1obYBMtCw%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:07.723456+03:00", 
        "dateModified": "2018-05-28T19:03:07.960503+03:00", 
        "id": "45baf4951469459394de757f4c50b394"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2018-05-28T19:03:08.092234+03:00", 
    "cancellationOf": "tender", 
    "id": "5b7b7e9fbe0340f5ad88eccc7ced1c51"
  }
}

