POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 160
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "Familiarization with bank asset", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentType": "x_dgfAssetFamiliarization"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents/f322908bc35041ca898fddc2f640e5d1
X-Content-Type-Options: nosniff

{
  "data": {
    "title": "Familiarization with bank asset", 
    "format": "offline/on-site-examination", 
    "accessDetails": "Familiar with asset: days, time, address", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:44.337012+03:00", 
    "documentType": "x_dgfAssetFamiliarization", 
    "dateModified": "2018-07-05T15:44:44.337032+03:00", 
    "id": "f322908bc35041ca898fddc2f640e5d1"
  }
}

