POST /api/2.4/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2262
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-06-09T19:02:59.179463"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "propertyLease", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "mode": "test", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "04121000-2", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827", 
          "endDate": "2018-06-02T19:02:58.713827"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.001
      }
    ], 
    "dgfID": "219560"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bacab87b56264568b59082d8ff724cce
X-Content-Type-Options: nosniff

{
  "access": {
    "token": "8164da3243104386b02a54665528347a"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-05-28-000001", 
    "enquiryPeriod": {
      "startDate": "2018-05-28T19:03:01.837027+03:00", 
      "endDate": "2018-06-08T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-06-08T20:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "title_en": "[TESTING] ", 
    "id": "bacab87b56264568b59082d8ff724cce", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-05-28T19:03:01.845486+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-05-28T19:03:01.837027+03:00", 
      "endDate": "2018-06-08T20:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-06-09T00:00:00+03:00"
    }, 
    "procurementMethodType": "propertyLease", 
    "dgfID": "219560", 
    "date": "2018-05-28T19:03:01.837027+03:00", 
    "rectificationPeriod": {
      "startDate": "2018-05-28T19:03:01.837027+03:00", 
      "endDate": "2018-06-03T20:00:00+03:00"
    }, 
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "4b1b5fe3c5b34c589d56658bfef148a9", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827+03:00", 
          "endDate": "2018-06-02T19:02:58.713827+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] ", 
    "awardCriteria": "highestCost"
  }
}

