PATCH /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/contracts/1bb4e628954a47f3a89125866c880f00?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 106
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2018-05-28T19:02:59.179463", 
      "endDate": "2019-05-28T19:02:59.179463"
    }
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "3b845b808a6345589d0777eeb3b79c6e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827+03:00", 
          "endDate": "2018-06-02T19:02:58.713827+03:00"
        }
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-05-28T19:02:59.179463+03:00", 
      "endDate": "2019-05-28T19:02:59.179463+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-05-28T19:03:06.703749+03:00", 
    "awardID": "708d3fdf13ac4868b0df09cf479ceb06", 
    "id": "1bb4e628954a47f3a89125866c880f00", 
    "contractID": "UA-EA-2018-05-28-000001-1"
  }
}

