GET /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents/806548dfbbbd4c64a320cd6a2493c942 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1ce52fd03573440ba6b1731c6c9cecea?KeyID=172d32c8&Signature=XDud%252BUyeXQuy9iOTIwWE5%2FBSWPmsPRKjG4XveLWCa1z%252B4JJKJDzTSOGkFVRpqZzb66rODALSr36dEGC%2F1qsXAQ%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:43.962162+03:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2018-07-05T15:44:43.962214+03:00", 
    "id": "806548dfbbbd4c64a320cd6a2493c942"
  }
}

