PATCH /api/2.4/auctions/ebc61cd1b78d417997d967283cdb2b3d?acc_token=3b1440659d9e444dbb274a8b875e4152 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 40
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active.tendering"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-07-05-000001", 
    "enquiryPeriod": {
      "startDate": "2018-07-05T15:44:39.495574+03:00", 
      "endDate": "2018-07-18T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-07-18T20:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "ebc61cd1b78d417997d967283cdb2b3d", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-07-05T15:44:39.553766+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-07-05T15:44:39.495574+03:00", 
      "endDate": "2018-07-18T20:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-07-19T00:00:00+03:00"
    }, 
    "procurementMethodType": "propertyLease", 
    "date": "2018-07-05T15:44:39.553766+03:00", 
    "lotIdentifier": "219560", 
    "rectificationPeriod": {
      "startDate": "2018-07-05T15:44:39.495574+03:00", 
      "endDate": "2018-07-13T20:00:00+03:00", 
      "invalidationDate": "2018-07-05T15:44:39.551607+03:00"
    }, 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "escalationClauses": [
          {
            "escalationPeriodicity": "P5M", 
            "conditions": "conditions description", 
            "escalationStepPercentage": 0.1, 
            "id": "79ddb6409d8e4319901d7ad507607908"
          }
        ], 
        "leaseDuration": "P10Y", 
        "taxHolidays": [
          {
            "taxHolidaysDuration": "P5M", 
            "conditions": "conditions description", 
            "id": "ca5a84973c38413a985e8cf36d496d2d", 
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }
          }
        ]
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "This field is required."
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "f94b10c6ace540dd946701ddc06d63fc", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-07-07T15:44:36.881991+03:00", 
          "endDate": "2018-07-10T15:44:36.881991+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

