POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/contracts/bf54ce84c6e6418382f49614f55d0101/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 351
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9b917efd600c445fad8457fd30f5cc5b?KeyID=172d32c8&Signature=4CcD6OI2rjqfEBygj%2BOhQTtr5TX4kFEtbM7W7Aq0LHcKfRU2DlBffBtG%2BsmrmBWC2SJosEt1dlExN%2BuzX5lwAg%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/contracts/bf54ce84c6e6418382f49614f55d0101/documents/962a2dccfd3248178dba9a291dfae225
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9b917efd600c445fad8457fd30f5cc5b?KeyID=172d32c8&Signature=d4SD5yjKKpZpExDc%2Fngc5rgeUSnIs1YOHk1gBD%2F0ndHMuBDR5t0PKoezrR7km0HjeOBcStVCrTJsOUoxoAerDA%253D%253D", 
    "title": "contract_first_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:46.883617+03:00", 
    "dateModified": "2018-07-05T15:44:46.883639+03:00", 
    "id": "962a2dccfd3248178dba9a291dfae225"
  }
}

