GET /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d36b0eb738984a60905854537a960795?KeyID=7149c8cc&Signature=oYC9e9WVmL4jM%252BhzrEnL7c6Nibmk1tAHoipDXjtyT61Q3j0ce1aPr0yJIMjPWyGXS3QB3hXNxv0%252BrhQXcpTrDA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-05-28T19:03:04.824043+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2018-05-28T19:03:04.824083+03:00", 
      "id": "2bb61a55cf5b4a8386260ac1a4cad34c"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b0696fd30a8441339034a0bedfeac17d?KeyID=7149c8cc&Signature=OqqMTmnanG%2FNPRbSjfZQkvve8ToxfFFA6UAJ22da%252BbRQ%2FZ7x7b5uqg5I%2FgnjqRhiC2leHG%252BT9X6W6xJbCFznCQ%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2018-05-28T19:03:04.874619+03:00", 
      "dateModified": "2018-05-28T19:03:04.929762+03:00", 
      "id": "882f19abea9041a2adc123890e947ebb"
    }, 
    {
      "index": 1, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "First illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1fcf682d16be4b55bab89065a0d9b5bb?KeyID=7149c8cc&Signature=0sMj57ikTcJbcIDCbBhHxhs6N%2Fta3ixRc1IySJnogUHEOxcw6p5%2FUSy9BxMGdvNVfdiiG2Y1W5Fhdcja%252BrqOBg%253D%253D", 
      "title": "first_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-05-28T19:03:04.990914+03:00", 
      "documentType": "illustration", 
      "dateModified": "2018-05-28T19:03:04.990934+03:00", 
      "id": "c6bd2aaef7cf42c5ba4f0dfad08285e2"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Second illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59a4408f99224306b2582176ca2bda32?KeyID=7149c8cc&Signature=VxN7Lt4LBsnxm4RQWy146688XcEKpVkJ1ofItTIRC55pCuA2oh%2FVxBZRVv%2F0lTC3LXKNmwF%2F78mt68XuuQl4AA%253D%253D", 
      "title": "second_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-05-28T19:03:05.055484+03:00", 
      "documentType": "illustration", 
      "dateModified": "2018-05-28T19:03:05.055508+03:00", 
      "id": "db649c26ced64a8292a91f14c2bd4b59"
    }, 
    {
      "index": 2, 
      "hash": "md5:00000000000000000000000000000000", 
      "description": "Third illustration description", 
      "format": "image/jpeg", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/73e7a9a343f84bd9941b2900ae031137?KeyID=7149c8cc&Signature=08nEK8j1PputzfNx7Db6qC%252BheWVbyrDCG8bFpl25q0ad%252BJD7Woa48SmacTzEhvPel5L3t5%2FCHEgq7jy82bRKCQ%253D%253D", 
      "title": "third_illustration.jpeg", 
      "documentOf": "tender", 
      "datePublished": "2018-05-28T19:03:05.101025+03:00", 
      "documentType": "illustration", 
      "dateModified": "2018-05-28T19:03:05.101047+03:00", 
      "id": "2c5c4017cc7d4001864e173fc897ffd1"
    }
  ]
}

