GET /api/2.4/auctions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "next_page": {
    "path": "/api/2.4/auctions?offset=2018-07-05T15%3A44%3A43.541215%2B03%3A00", 
    "uri": "http://api-sandbox.ea.openprocurement.org/api/2.4/auctions?offset=2018-07-05T15%3A44%3A43.541215%2B03%3A00", 
    "offset": "2018-07-05T15:44:43.541215+03:00"
  }, 
  "data": [
    {
      "id": "bf6575a30f2c4465ae43e06981df3b5a", 
      "dateModified": "2018-07-05T15:44:43.541215+03:00"
    }
  ]
}

