POST /api/2.4/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2552
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "lotIdentifier": "219560", 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "escalationClauses": [
          {
            "conditions": "conditions description", 
            "escalationPeriodicity": "P5M", 
            "escalationStepPercentage": 0.1
          }
        ], 
        "leaseDuration": "P10Y", 
        "taxHolidays": [
          {
            "taxHolidaysDuration": "P5M", 
            "conditions": "conditions description", 
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }
          }
        ]
      }
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-07-17T15:44:37.150620+03:00"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "propertyLease", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "04121000-2", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "This field is required."
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "contractPeriod": {
          "startDate": "2018-07-07T15:44:36.881991", 
          "endDate": "2018-07-10T15:44:36.881991"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.001
      }
    ], 
    "mode": "test"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/6ea97f1e851943f8bfd174381fc1deb3
X-Content-Type-Options: nosniff

{
  "access": {
    "transfer": "2b94cb50e1144370af11c7a8fa287075", 
    "token": "706b59321ec64d57964a2f21fde4f5de"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-07-05-000001", 
    "enquiryPeriod": {
      "startDate": "2018-07-05T15:44:40.361611+03:00", 
      "endDate": "2018-07-16T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-07-16T20:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "title_en": "[TESTING] ", 
    "id": "6ea97f1e851943f8bfd174381fc1deb3", 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-07-05T15:44:40.372647+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-07-05T15:44:40.361611+03:00", 
      "endDate": "2018-07-16T20:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-07-17T00:00:00+03:00"
    }, 
    "procurementMethodType": "propertyLease", 
    "date": "2018-07-05T15:44:40.361611+03:00", 
    "lotIdentifier": "219560", 
    "rectificationPeriod": {
      "startDate": "2018-07-05T15:44:40.361611+03:00", 
      "endDate": "2018-07-11T20:00:00+03:00"
    }, 
    "contractTerms": {
      "type": "lease", 
      "leaseTerms": {
        "escalationClauses": [
          {
            "escalationPeriodicity": "P5M", 
            "conditions": "conditions description", 
            "escalationStepPercentage": 0.1, 
            "id": "8e7b12ee3c444f46af72606c4d10b2ab"
          }
        ], 
        "leaseDuration": "P10Y", 
        "taxHolidays": [
          {
            "taxHolidaysDuration": "P5M", 
            "conditions": "conditions description", 
            "id": "abb5892c185c4994bf7f5404310f9337", 
            "value": {
              "currency": "UAH", 
              "amount": 100.0, 
              "valueAddedTaxIncluded": true
            }
          }
        ]
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "This field is required."
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "74682b00914943b6a8c1145e455e9d75", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-07-07T15:44:36.881991+03:00", 
          "endDate": "2018-07-10T15:44:36.881991+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] ", 
    "awardCriteria": "highestCost"
  }
}

