GET /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-05-28-000001", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/246d20f56b0a4601bd4b5ddd3ac636e9", 
    "enquiryPeriod": {
      "startDate": "2018-05-21T19:02:58.713827+03:00", 
      "endDate": "2018-05-28T19:02:58.713827+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-05-28T19:46:58.713827+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2018-05-28T19:03:05.241690+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "22c3e98b31fd4c50bab5639de0668f1c", 
        "questionOf": "tender"
      }
    ], 
    "owner": "broker", 
    "id": "246d20f56b0a4601bd4b5ddd3ac636e9", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d36b0eb738984a60905854537a960795?KeyID=7149c8cc&Signature=oYC9e9WVmL4jM%252BhzrEnL7c6Nibmk1tAHoipDXjtyT61Q3j0ce1aPr0yJIMjPWyGXS3QB3hXNxv0%252BrhQXcpTrDA%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:04.824043+03:00", 
        "documentType": "technicalSpecifications", 
        "dateModified": "2018-05-28T19:03:04.824083+03:00", 
        "id": "2bb61a55cf5b4a8386260ac1a4cad34c"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/42f468f963964ac0883313db87abc294?KeyID=7149c8cc&Signature=XRuGZP2eAk2I7vRsPppBUKCGQWoWEcTdD7Cn%2FQJFqHsAzhj5y9yj75Af3iKYenLWwy01%2Fj7A4jHQR%252BZkIbI4CA%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:04.874619+03:00", 
        "dateModified": "2018-05-28T19:03:04.874644+03:00", 
        "id": "882f19abea9041a2adc123890e947ebb"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b0696fd30a8441339034a0bedfeac17d?KeyID=7149c8cc&Signature=OqqMTmnanG%2FNPRbSjfZQkvve8ToxfFFA6UAJ22da%252BbRQ%2FZ7x7b5uqg5I%2FgnjqRhiC2leHG%252BT9X6W6xJbCFznCQ%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:04.874619+03:00", 
        "dateModified": "2018-05-28T19:03:04.929762+03:00", 
        "id": "882f19abea9041a2adc123890e947ebb"
      }, 
      {
        "index": 1, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "First illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1fcf682d16be4b55bab89065a0d9b5bb?KeyID=7149c8cc&Signature=0sMj57ikTcJbcIDCbBhHxhs6N%2Fta3ixRc1IySJnogUHEOxcw6p5%2FUSy9BxMGdvNVfdiiG2Y1W5Fhdcja%252BrqOBg%253D%253D", 
        "title": "first_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:04.990914+03:00", 
        "documentType": "illustration", 
        "dateModified": "2018-05-28T19:03:04.990934+03:00", 
        "id": "c6bd2aaef7cf42c5ba4f0dfad08285e2"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Second illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59a4408f99224306b2582176ca2bda32?KeyID=7149c8cc&Signature=VxN7Lt4LBsnxm4RQWy146688XcEKpVkJ1ofItTIRC55pCuA2oh%2FVxBZRVv%2F0lTC3LXKNmwF%2F78mt68XuuQl4AA%253D%253D", 
        "title": "second_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:05.055484+03:00", 
        "documentType": "illustration", 
        "dateModified": "2018-05-28T19:03:05.055508+03:00", 
        "id": "db649c26ced64a8292a91f14c2bd4b59"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Third illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/73e7a9a343f84bd9941b2900ae031137?KeyID=7149c8cc&Signature=08nEK8j1PputzfNx7Db6qC%252BheWVbyrDCG8bFpl25q0ad%252BJD7Woa48SmacTzEhvPel5L3t5%2FCHEgq7jy82bRKCQ%253D%253D", 
        "title": "third_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:05.101025+03:00", 
        "documentType": "illustration", 
        "dateModified": "2018-05-28T19:03:05.101047+03:00", 
        "id": "2c5c4017cc7d4001864e173fc897ffd1"
      }, 
      {
        "title": "Familiarization with bank asset", 
        "format": "offline/on-site-examination", 
        "accessDetails": "Familiar with asset: days, time, address", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:05.169280+03:00", 
        "documentType": "x_dgfAssetFamiliarization", 
        "dateModified": "2018-05-28T19:03:05.169300+03:00", 
        "id": "f08b3a9250ab4539b492080a538da808"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-05-28T19:03:05.823039+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2018-05-21T19:02:58.713827+03:00", 
      "endDate": "2018-05-28T19:02:58.713827+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2018-05-28T19:02:58.713827+03:00", 
      "shouldStartAfter": "2018-05-29T00:00:00+03:00"
    }, 
    "procurementMethodType": "propertyLease", 
    "dgfID": "219560", 
    "date": "2018-05-28T19:03:04.480367+03:00", 
    "rectificationPeriod": {
      "startDate": "2018-05-21T19:02:58.713827+03:00", 
      "endDate": "2018-05-22T19:02:58.713827+03:00", 
      "invalidationDate": "2018-05-28T19:03:05.169439+03:00"
    }, 
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "3b845b808a6345589d0777eeb3b79c6e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827+03:00", 
          "endDate": "2018-06-02T19:02:58.713827+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

