PATCH /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/contracts/bf54ce84c6e6418382f49614f55d0101?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2018-07-05T15:44:47.244215+03:00"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9b917efd600c445fad8457fd30f5cc5b?KeyID=172d32c8&Signature=d4SD5yjKKpZpExDc%2Fngc5rgeUSnIs1YOHk1gBD%2F0ndHMuBDR5t0PKoezrR7km0HjeOBcStVCrTJsOUoxoAerDA%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:46.883617+03:00", 
        "dateModified": "2018-07-05T15:44:46.883639+03:00", 
        "id": "962a2dccfd3248178dba9a291dfae225"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/969aa13f4a1c435ab43c7b427af92ab3?KeyID=172d32c8&Signature=0iJX1gukI8TnCgWs%2FyLb%2FB%2F7%252BKDkJPwE0sJP7On10lxJ4oMN0jcmu7yPIVq1PhTZzNOyjOmgB24pfQnDjtT9CQ%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:47.054363+03:00", 
        "dateModified": "2018-07-05T15:44:47.054390+03:00", 
        "id": "7ddd64f00176447f9efe57751f7361fe"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "This field is required."
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "34d79ae5dcdb4eb4b61dba5d6a4000d7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-07-07T15:44:36.881991+03:00", 
          "endDate": "2018-07-10T15:44:36.881991+03:00"
        }
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2018-07-05T15:44:37.150620+03:00", 
      "endDate": "2019-07-05T15:44:37.150620+03:00"
    }, 
    "dateSigned": "2018-07-05T15:44:47.244215+03:00", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-07-05T15:44:47.325639+03:00", 
    "awardID": "c525bd6997924149a071ab0d845875f0", 
    "id": "bf54ce84c6e6418382f49614f55d0101", 
    "contractID": "UA-EA-2018-07-05-000001-1"
  }
}

