GET /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/bids/4ed57eda57b941399523f19f03b9ada4?acc_token=650aaa4270024deaac41cb856120c3c5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/bids/4ed57eda57b941399523f19f03b9ada4/documents/75135cb499834e5ca718f462e5d3c1e7?download=52acfea5369d48cb85f0bad1a27eaf23", 
        "title": "Proposal.pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-05-28T19:03:05.533715+03:00", 
        "dateModified": "2018-05-28T19:03:05.533744+03:00", 
        "id": "75135cb499834e5ca718f462e5d3c1e7"
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-05-28T19:03:05.400869+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "owner": "broker", 
    "id": "4ed57eda57b941399523f19f03b9ada4", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/246d20f56b0a4601bd4b5ddd3ac636e9?key_for_bid=4ed57eda57b941399523f19f03b9ada4"
  }
}

