POST /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/awards/708d3fdf13ac4868b0df09cf479ceb06/documents?acc_token=ad29e002be7540eba7ee46592248215f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 381
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f4402467721a4eee9ef72e70a4ff04f1?KeyID=7149c8cc&Signature=ktH7wX%2BrsWWNqI7oijR9YIgHAM7Lw%2FCjN%2FHF5muEKERp53oy9RuOaTWLxVshntmKtvp3yA81ihypWST0wdI7DA%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/awards/708d3fdf13ac4868b0df09cf479ceb06/documents/627c441c40dd4635ac691c549cacba8c
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "bid_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f4402467721a4eee9ef72e70a4ff04f1?KeyID=7149c8cc&Signature=FWQKkrdr%2Fo95YrYaNn881fhFABAvU2yXd77Dz0R8h01tiB4%2FFX4efEmV4eK9jcB2Kmps5x0jStFNTA7Kxl4YBA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-05-28T19:03:06.372223+03:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2018-05-28T19:03:06.372249+03:00", 
    "id": "627c441c40dd4635ac691c549cacba8c"
  }
}

