PATCH /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/awards/c525bd6997924149a071ab0d845875f0?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "status": "active", 
    "paymentPeriod": {
      "startDate": "2018-07-05T15:44:45.557459+03:00", 
      "endDate": "2018-07-05T15:44:46.426889+03:00"
    }, 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "bid_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/634b8812abec4bed88f99fae0b19e0ed?KeyID=172d32c8&Signature=AM16nchbBzt03Ga62R68itoWzRR1XZean6QW6kjlgzA7kwBza3Nm%252BfNpS0P%252BgyngKTjIu5Rq3KE7jjhkYiaWCQ%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:46.033757+03:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-07-05T15:44:46.033778+03:00", 
        "id": "045ca245f33740a7a0e0d3cea8dc7b4e"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "auction_owner", 
        "title": "SignedAuctionProtocol.pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/87da15a07f5e4809a4b4a2ab9c16bae1?KeyID=172d32c8&Signature=12lOdsrwdSYqiYe%252BaDBYs444ZR61xmz2cuUwu6T6zEOWS3cBWSbgY%2FqEy5dlgw7PVR9npNInMuvdgSucfh8%252BDA%253D%253D", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2018-07-05T15:44:46.170042+03:00", 
        "documentType": "auctionProtocol", 
        "dateModified": "2018-07-05T15:44:46.170096+03:00", 
        "id": "850eff6be8de4f70922aa99415eec581"
      }
    ], 
    "verificationPeriod": {
      "startDate": "2018-07-05T15:44:45.557459+03:00", 
      "endDate": "2018-07-05T15:44:46.310338+03:00"
    }, 
    "complaintPeriod": {
      "startDate": "2018-07-05T15:44:45.557459+03:00", 
      "endDate": "2018-07-05T15:44:46.426889+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "signingPeriod": {
      "startDate": "2018-07-05T15:44:45.557459+03:00", 
      "endDate": "2018-08-02T18:00:00.557459+03:00"
    }, 
    "bid_id": "19d92b47538f4bcfb7d087eaabb84afa", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2018-07-05T15:44:46.433858+03:00", 
    "id": "c525bd6997924149a071ab0d845875f0"
  }
}

