POST /api/2.4/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 3158
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "description_en": "Cases with state awards", 
    "description": "футляри до державних нагород", 
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-06-11"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "propertyLease", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "description_ru": "футляры к государственным наградам", 
    "dgfID": "219560", 
    "title_ru": "футляры к государственным наградам", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "04121000-2", 
          "description": "Земельні ділянки"
        }, 
        "description_en": "Cases with state awards", 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "description_ru": "футляры к государственным наградам", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827", 
          "endDate": "2018-06-02T19:02:58.713827"
        }
      }
    ], 
    "title_en": "Cases with state awards", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/e589f73396de4c75bbba0ef0a3a1d971
X-Content-Type-Options: nosniff

{
  "access": {
    "token": "f047d95916a74118bb883896564b9a3f"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-05-28-000003", 
    "enquiryPeriod": {
      "startDate": "2018-05-28T19:03:04.589432+03:00", 
      "endDate": "2018-06-10T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-06-10T20:00:00+03:00", 
    "awardCriteria": "highestCost", 
    "owner": "broker", 
    "id": "e589f73396de4c75bbba0ef0a3a1d971", 
    "description": "футляри до державних нагород", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-06-11T00:00:00+03:00"
    }, 
    "description_ru": "футляры к государственным наградам", 
    "dateModified": "2018-05-28T19:03:04.598947+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-05-28T19:03:04.589432+03:00", 
      "endDate": "2018-06-10T20:00:00+03:00"
    }, 
    "title_en": "Cases with state awards", 
    "procurementMethodType": "propertyLease", 
    "description_en": "Cases with state awards", 
    "dgfID": "219560", 
    "date": "2018-05-28T19:03:04.589432+03:00", 
    "rectificationPeriod": {
      "startDate": "2018-05-28T19:03:04.589432+03:00", 
      "endDate": "2018-06-05T20:00:00+03:00"
    }, 
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "description_en": "Cases with state awards", 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "description_ru": "футляры к государственным наградам", 
        "id": "e9e1755a5a9245b0af8fc25870a07245", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827+03:00", 
          "endDate": "2018-06-02T19:02:58.713827+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "title_ru": "футляры к государственным наградам", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

