GET /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "status": "pending.verification", 
      "paymentPeriod": {
        "startDate": "2018-05-28T19:03:06.074292+03:00", 
        "endDate": "2018-06-26T18:00:00+03:00"
      }, 
      "verificationPeriod": {
        "startDate": "2018-05-28T19:03:06.074292+03:00", 
        "endDate": "2018-06-06T18:00:00+03:00"
      }, 
      "signingPeriod": {
        "startDate": "2018-05-28T19:03:06.074292+03:00", 
        "endDate": "2018-06-26T18:00:00+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-05-28T19:03:06.074292+03:00"
      }, 
      "bid_id": "3ce3413a56584eb1a7a870e01121effb", 
      "value": {
        "currency": "UAH", 
        "amount": 501.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-05-28T19:03:06.074292+03:00", 
      "id": "708d3fdf13ac4868b0df09cf479ceb06"
    }, 
    {
      "status": "pending.waiting", 
      "complaintPeriod": {
        "startDate": "2018-05-28T19:03:06.074292+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "4ed57eda57b941399523f19f03b9ada4", 
      "value": {
        "currency": "UAH", 
        "amount": 500.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-05-28T19:03:06.074292+03:00", 
      "id": "623e2ec3b03a4cbf82485097b8c3cc91"
    }
  ]
}

