GET /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/awards HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "status": "pending.verification", 
      "paymentPeriod": {
        "startDate": "2018-07-05T15:44:45.557459+03:00", 
        "endDate": "2018-08-02T18:00:00.557459+03:00"
      }, 
      "verificationPeriod": {
        "startDate": "2018-07-05T15:44:45.557459+03:00", 
        "endDate": "2018-07-13T18:00:00.557459+03:00"
      }, 
      "signingPeriod": {
        "startDate": "2018-07-05T15:44:45.557459+03:00", 
        "endDate": "2018-08-02T18:00:00.557459+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "aagt@gmail.com", 
            "telephone": "+380 (322) 91-69-30", 
            "name": "Андрій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137226", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Книга»", 
          "address": {
            "postalCode": "79013", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 34", 
            "region": "м. Львів", 
            "locality": "м. Львів"
          }
        }
      ], 
      "complaintPeriod": {
        "startDate": "2018-07-05T15:44:45.557459+03:00"
      }, 
      "bid_id": "19d92b47538f4bcfb7d087eaabb84afa", 
      "value": {
        "currency": "UAH", 
        "amount": 501.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-07-05T15:44:45.557459+03:00", 
      "id": "c525bd6997924149a071ab0d845875f0"
    }, 
    {
      "status": "pending.waiting", 
      "complaintPeriod": {
        "startDate": "2018-07-05T15:44:45.557459+03:00"
      }, 
      "suppliers": [
        {
          "contactPoint": {
            "email": "soleksuk@gmail.com", 
            "telephone": "+380 (432) 21-69-30", 
            "name": "Сергій Олексюк"
          }, 
          "identifier": {
            "scheme": "UA-EDR", 
            "id": "00137256", 
            "uri": "http://www.sc.gov.ua/"
          }, 
          "name": "ДКП «Школяр»", 
          "address": {
            "postalCode": "21100", 
            "countryName": "Україна", 
            "streetAddress": "вул. Островського, 33", 
            "region": "м. Вінниця", 
            "locality": "м. Вінниця"
          }
        }
      ], 
      "bid_id": "192d6412b08e4743b9cf6d267538c72a", 
      "value": {
        "currency": "UAH", 
        "amount": 500.0, 
        "valueAddedTaxIncluded": true
      }, 
      "date": "2018-07-05T15:44:45.557459+03:00", 
      "id": "94df6a7fba0e49749ed3009cf0d1feae"
    }
  ]
}

