GET /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2018-05-28T19:03:05.241690+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "22c3e98b31fd4c50bab5639de0668f1c", 
      "questionOf": "tender"
    }
  ]
}

