GET /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/questions HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": [
    {
      "description": "Просимо додати таблицю потрібної калорійності харчування", 
      "title": "Калорійність", 
      "date": "2018-07-05T15:44:44.418932+03:00", 
      "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
      "id": "7a8ea78f01b9408b9c4700de5409f22c", 
      "questionOf": "tender"
    }
  ]
}

