PATCH /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2230
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2018-06-11"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "propertyLease", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "dgfID": "219560", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "id": "04121000-2", 
          "description": "Земельні ділянки"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827", 
          "endDate": "2018-06-02T19:02:58.713827"
        }, 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5.001
      }
    ], 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}


403 Forbidden
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "status": "error", 
  "errors": [
    {
      "description": "Auction can be edited only during the rectification period: from (2018-05-14T19:03:04.732774+03:00) to (2018-05-22T19:03:04.732774+03:00).", 
      "location": "body", 
      "name": "data"
    }
  ]
}

