POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/awards/c525bd6997924149a071ab0d845875f0/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 383
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/87da15a07f5e4809a4b4a2ab9c16bae1?KeyID=172d32c8&Signature=K%2BU2mnmfTeZYdv2HODx3bhN6l7o%2FPtK1qBhl742tiTFXpp42l%2BeP8yg37kxBDgZ3jAqhCWQIPgfS%2BfHwK5ZYCQ%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/awards/c525bd6997924149a071ab0d845875f0/documents/850eff6be8de4f70922aa99415eec581
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "auction_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/87da15a07f5e4809a4b4a2ab9c16bae1?KeyID=172d32c8&Signature=12lOdsrwdSYqiYe%252BaDBYs444ZR61xmz2cuUwu6T6zEOWS3cBWSbgY%2FqEy5dlgw7PVR9npNInMuvdgSucfh8%252BDA%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:46.170042+03:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2018-07-05T15:44:46.170096+03:00", 
    "id": "850eff6be8de4f70922aa99415eec581"
  }
}

