POST /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/awards/708d3fdf13ac4868b0df09cf479ceb06/documents?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 385
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1ba9a8b51cd14c05aa42fef2bb3965db?KeyID=7149c8cc&Signature=muBdxzty2PgmXY%2BAnFhgHRne8Dy7aN%2FbrbgUblS74CnzEJxu%2FKCtb1zLcQ7nh3%2Bbb4qQAaJnMxWdDwdc%2FaQKCg%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/awards/708d3fdf13ac4868b0df09cf479ceb06/documents/77e9d9a7876740f1a64931dd4f96989c
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "author": "auction_owner", 
    "title": "SignedAuctionProtocol.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1ba9a8b51cd14c05aa42fef2bb3965db?KeyID=7149c8cc&Signature=z%2Ftx0X6an%252B1mIrbwMmuknuPp%252BFVzm3Ps4I%2FXguLCJe5mLZLoqJHlVkZq%252B93cTVvvsRiGx2ASxd%2FtV762p80VBw%253D%253D", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-05-28T19:03:06.459190+03:00", 
    "documentType": "auctionProtocol", 
    "dateModified": "2018-05-28T19:03:06.459214+03:00", 
    "id": "77e9d9a7876740f1a64931dd4f96989c"
  }
}

