PATCH /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2018-06-12T19:03:14.663047+03:00"
    }
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-EA-2018-05-28-000001", 
    "enquiryPeriod": {
      "startDate": "2018-05-28T19:03:04.480367+03:00", 
      "endDate": "2018-06-10T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "next_check": "2018-06-10T20:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "owner": "broker", 
    "id": "246d20f56b0a4601bd4b5ddd3ac636e9", 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "dateModified": "2018-05-28T19:03:04.702467+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2018-05-28T19:03:04.480367+03:00", 
      "endDate": "2018-06-10T20:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2018-06-11T00:00:00+03:00"
    }, 
    "procurementMethodType": "propertyLease", 
    "dgfID": "219560", 
    "date": "2018-05-28T19:03:04.480367+03:00", 
    "rectificationPeriod": {
      "startDate": "2018-05-28T19:03:04.480367+03:00", 
      "endDate": "2018-06-05T20:00:00+03:00", 
      "invalidationDate": "2018-05-28T19:03:04.701084+03:00"
    }, 
    "contractTerms": {
      "contractType": "lease", 
      "leaseTerms": {
        "leaseDuration": "P10Y"
      }
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV-PS", 
          "description": "Земельні ділянки", 
          "id": "04121000-2"
        }, 
        "additionalClassifications": [
          {
            "scheme": "CPVS", 
            "id": "PA01-7", 
            "description": "Оренда"
          }
        ], 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "quantity": 5.001, 
        "id": "3b845b808a6345589d0777eeb3b79c6e", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "contractPeriod": {
          "startDate": "2018-05-30T19:02:58.713827+03:00", 
          "endDate": "2018-06-02T19:02:58.713827+03:00"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardCriteria": "highestCost"
  }
}

