POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/cancellations?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/cancellations/85e3350a80ab47548c6933c01fe8b85e
X-Content-Type-Options: nosniff

{
  "data": {
    "date": "2018-07-05T15:44:47.497188+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "85e3350a80ab47548c6933c01fe8b85e"
  }
}

