PUT /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/cancellations/85e3350a80ab47548c6933c01fe8b85e/documents/c4eb9970b6694811bb16c782ca84b967?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 331
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a9c682c7a1247409b01e5df7baa67e6?KeyID=172d32c8&Signature=GKgfs1Zu%2BpJm4hfO83c21wmQAvJo5mpcat7769QW1ZCddLq8MtAuqogldtj8P%2F0YubAilfzrvvwVUfjSCuGLBA%3D%3D", 
    "title": "Notice-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Changed description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/1a9c682c7a1247409b01e5df7baa67e6?KeyID=172d32c8&Signature=QMKBUG9URxfQnxjPVz00I7zJwZljZ2HV%2F5hh9uYg4cg7kmVCpvWKIQ%252Bf1bPSuVgzflIci5Z93BnbFGI7jXVhAg%253D%253D", 
    "title": "Notice-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:47.635718+03:00", 
    "dateModified": "2018-07-05T15:44:47.965256+03:00", 
    "id": "c4eb9970b6694811bb16c782ca84b967"
  }
}

