POST /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/documents?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 434
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59a4408f99224306b2582176ca2bda32?KeyID=7149c8cc&Signature=JhDc6%2BOC2Tbf15iDLCR7WV4VP6lxh1qswnBMqDtoBUom1ycV2R9ZjLtqXh3hiZ%2BByfhOmd%2FMM9cNv3k9fLdKAg%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/documents/db649c26ced64a8292a91f14c2bd4b59
X-Content-Type-Options: nosniff

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/59a4408f99224306b2582176ca2bda32?KeyID=7149c8cc&Signature=VxN7Lt4LBsnxm4RQWy146688XcEKpVkJ1ofItTIRC55pCuA2oh%2FVxBZRVv%2F0lTC3LXKNmwF%2F78mt68XuuQl4AA%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2018-05-28T19:03:05.055484+03:00", 
    "documentType": "illustration", 
    "dateModified": "2018-05-28T19:03:05.055508+03:00", 
    "id": "db649c26ced64a8292a91f14c2bd4b59"
  }
}

