POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 432
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a1cbeaa2c76140f8b37f0af516a23560?KeyID=172d32c8&Signature=n1wwvsam8m3UpY4IJQkadbUiud4rTmawTsi%2Bz6bpWJmeNclML2hDHM2vi9bpUjclY4qMGsWJ6RkLo%2FKWtDFjDg%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents/dc25aac992074754a54e622b75ccf552
X-Content-Type-Options: nosniff

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/a1cbeaa2c76140f8b37f0af516a23560?KeyID=172d32c8&Signature=FAkPz4qiw3ChZWW53oZeSn9ukX6GzYrNI4fClQEmgJVhGyjOqjvw0rKs3zgGYAwRg%2FpOC13F%2F6vUYQw2DAhxCw%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:44.217182+03:00", 
    "documentType": "illustration", 
    "dateModified": "2018-07-05T15:44:44.217203+03:00", 
    "id": "dc25aac992074754a54e622b75ccf552"
  }
}

