POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 336
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c62be1575beb463786d360a782b04a07?KeyID=172d32c8&Signature=laHrKHkqys3U5SL%2BkDcmHV17ZerGCFpHrnds%2FOHYIHu1UPHq855BauPd69w46aqvgmmN50wJ9cphwi9TRT3FBw%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents/1ee1b150bb7c4d4197379afa2e86f40a
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c62be1575beb463786d360a782b04a07?KeyID=172d32c8&Signature=dq9l6ox%252B9bq5wtran%2FzRS74f6mVwD%252Bmw3iST96fFDO7OkbCnzDM2GeAK%2FbePequlPdkoHeILvxVjDyjauAhdCg%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:44.029815+03:00", 
    "dateModified": "2018-07-05T15:44:44.029835+03:00", 
    "id": "1ee1b150bb7c4d4197379afa2e86f40a"
  }
}

