POST /api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents?acc_token=686740317fd249638e3ee0420d268ebf HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 436
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7a1640d5df0448cb9042c1410430a809?KeyID=172d32c8&Signature=McsENObOi5%2F%2Fr4VpcyF7Le1idsJxVyhb%2By2w7h%2Bnlrqn5M0VNACab5R5sM1bJtGjY6cnoL8iM2PmC87t%2FYCzDA%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/bf6575a30f2c4465ae43e06981df3b5a/documents/fbf05d710f3d4c19acd84b0f17017eea
X-Content-Type-Options: nosniff

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/7a1640d5df0448cb9042c1410430a809?KeyID=172d32c8&Signature=iY06XmBxdm5LarAm6R6Z8ggoBnSqJE0dzJ03C9WO70NZ7Yj9nibjk4RfdxC%2FKrvTfCD59I1mxLLXqFYCryXvDA%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2018-07-05T15:44:44.264917+03:00", 
    "documentType": "illustration", 
    "dateModified": "2018-07-05T15:44:44.264939+03:00", 
    "id": "fbf05d710f3d4c19acd84b0f17017eea"
  }
}

