POST /api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/documents?acc_token=06bf67377235444180324a6ec7a7b41d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 417
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d36b0eb738984a60905854537a960795?KeyID=7149c8cc&Signature=zF%2FDQ%2BwGfUxGhzdH0WUV5CQv4Gw%2BVqcLMGRtZWHXO2eL2RL%2FhsL79opqAMj6z3%2B5FzxGycrLGf79AwYPvydkCA%3D%3D", 
    "format": "application/pdf", 
    "documentType": "technicalSpecifications"
  }
}


201 Created
Content-Type: application/json
Location: http://api-sandbox.ea.openprocurement.org/api/2.4/auctions/246d20f56b0a4601bd4b5ddd3ac636e9/documents/2bb61a55cf5b4a8386260ac1a4cad34c
X-Content-Type-Options: nosniff

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d36b0eb738984a60905854537a960795?KeyID=7149c8cc&Signature=oYC9e9WVmL4jM%252BhzrEnL7c6Nibmk1tAHoipDXjtyT61Q3j0ce1aPr0yJIMjPWyGXS3QB3hXNxv0%252BrhQXcpTrDA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2018-05-28T19:03:04.824043+03:00", 
    "documentType": "technicalSpecifications", 
    "dateModified": "2018-05-28T19:03:04.824083+03:00", 
    "id": "2bb61a55cf5b4a8386260ac1a4cad34c"
  }
}

